### ISSUE TITLE
Cannot start an application, React scripts should be updated to 3.4.0

### ISSUE THREAD

**Issue by karelkral** [Roaders/inversify-constructor-injection#1]
Hello, an application created with `npx create-react-app-inversify my-app` cannot start. 

`
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (F:\Repos\CICD\Src\SandBox\DevOpsExtension\InversifyTest\my-app\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (F:\Repos\CICD\Src\SandBox\DevOpsExtension\InversifyTest\my-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (F:\Repos\CICD\Src\SandBox\DevOpsExtension\InversifyTest\my-app\node_modules\express\lib\router\index.js:317:13)
    at F:\Repos\CICD\Src\SandBox\DevOpsExtension\InversifyTest\my-app\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (F:\Repos\CICD\Src\SandBox\DevOpsExtension\InversifyTest\my-app\node_modules\express\lib\router\index.js:335:12)
    at next (F:\Repos\CICD\Src\SandBox\DevOpsExtension\InversifyTest\my-app\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (F:\Repos\CICD\Src\SandBox\DevOpsExtension\InversifyTest\my-app\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (F:\Repos\CICD\Src\SandBox\DevOpsExtension\InversifyTest\my-app\node_modules\express\lib\router\layer.js:95:5)
`

As I found in [this issue](https://stackoverflow.com/questions/60236986/the-below-error-occurred-after-running-the-command-ionic5-serve), update react-script to 3.4.0 should be sufficient solution. But your `react-scripts-inversify` is forked from some older version.

**Comment by Roaders** [comment]
Should be fixed now. Can you give it a go and close this issue if it's fixed.

**Comment by Roaders** [comment]
Looks like a new version of some other dependency was released that was installed and broke this. When the `create-react` script runs it just installs the latest version of all the packages so it can break with new releases.
